/**
 * AdmitStudent — create a student record and their initial enrollment as ONE
 * atomic operation (architecture review F-1 / ADR-7.2). If the enrollment write
 * fails, the student create rolls back too — no orphaned student without a
 * placement. Permission-gated and audited.
 *
 * Phase 3 (Workstream C): admissionSession is required, matricule is
 * auto-generated by default (manual override allowed), denormalized
 * facultyId/departmentId are set, manual matricules are format-validated, and
 * the admitting officer is faculty-scoped.
 */
import { SessionContext } from "../../../domain/value-objects/SessionContext";
import { RecordsError } from "../../../domain/errors/records";
import type { Student } from "../../../domain/entities";
import type { StudentEnrollment } from "../../../domain/entities/enrollment";
import type { UnitOfWork } from "../../ports/UnitOfWork";
import type { AuthorizedUseCase } from "../../authorization/AuthorizedUseCase";
import type {
  GenerateMatricule,
  MatriculeSettingsPort,
} from "../../services/GenerateMatricule";
import { requireInFacultyScope } from "../../authorization/institutionScope";

export interface AdmitStudentInput {
  fullName: string;
  matricNumber?: string;
  regNumber?: string;
  programmeId: string;
  levelId: string;
  facultyId?: string;
  departmentId?: string;
  admissionSession: string;
  previousStudentId?: string;
}

export interface AdmitStudentResult {
  student: Student;
  enrollment: StudentEnrollment;
}

export class AdmitStudent implements AuthorizedUseCase<
  AdmitStudentInput,
  AdmitStudentResult
> {
  readonly name = "AdmitStudent";
  readonly requiredPermissions = ["students.create"];

  constructor(
    private readonly uow: UnitOfWork,
    private readonly generate: GenerateMatricule,
    private readonly settings: MatriculeSettingsPort,
  ) {}

  async execute(
    input: AdmitStudentInput,
    session: SessionContext,
  ): Promise<AdmitStudentResult> {
    if (input.fullName.trim().length === 0) {
      throw new RecordsError("Full name must not be empty.", {
        fullName: "Full name must not be empty.",
      });
    }
    if (!input.admissionSession || input.admissionSession.trim().length === 0) {
      throw new RecordsError("Admission session must not be empty.", {
        admissionSession: "Admission session must not be empty.",
      });
    }

    // Faculty-scope guard: ALWAYS call — a faculty-scoped officer without a
    // facultyId in the input would otherwise bypass the check entirely.
    // requireInFacultyScope is a no-op for non-scoped sessions but THROWS for
    // faculty-scoped ones if facultyId is undefined or outside their set.
    requireInFacultyScope(input.facultyId, session);

    return this.uow.run(async (repos) => {
      // --- resolve / validate matricule ---
      let matric: string;
      const trimmed = input.matricNumber?.trim();
      if (trimmed) {
        // Manual override: validate against the configured format regex.
        const fmt = await this.settings.matriculeFormat();
        if (fmt) {
          let re: RegExp;
          try {
            re = new RegExp(`^(?:${fmt})$`);
          } catch {
            throw new RecordsError("Configured matricule format is invalid.");
          }
          if (!re.test(trimmed)) {
            throw new RecordsError(
              "Matricule does not match the required format.",
              { matricNumber: "Invalid format." },
            );
          }
        }
        matric = trimmed;
      } else {
        // Auto-generate: facultyId is required for the counter key.
        if (!input.facultyId) {
          throw new RecordsError(
            "facultyId is required when auto-generating a matricule.",
            {
              facultyId: "facultyId is required for auto-generated matricules.",
            },
          );
        }
        matric = await this.generate.generate(
          {
            institutionId: null,
            facultyId: input.facultyId,
            departmentId: input.departmentId,
            admissionSession: input.admissionSession,
          },
          repos,
          "reserve",
        );
      }

      // --- uniqueness guard ---
      if (await repos.students.findByMatric(matric)) {
        const msg = `Matric number "${matric}" is already in use.`;
        throw new RecordsError(msg, { matricNumber: msg });
      }

      // --- create student ---
      const student = await repos.students.create({
        matricNumber: matric,
        fullName: input.fullName,
        regNumber: input.regNumber,
        programmeId: input.programmeId,
        levelId: input.levelId,
        facultyId: input.facultyId,
        departmentId: input.departmentId,
        admissionSession: input.admissionSession,
        previousStudentId: input.previousStudentId,
        status: "ACTIVE",
      });

      // --- initial enrollment ---
      const enrollment = await repos.enrollments.create({
        studentId: student.id,
        programmeId: input.programmeId,
        levelId: input.levelId,
        fromSession: input.admissionSession,
        isCurrent: true,
      });

      // --- audit ---
      await repos.audit.record({
        userId: session.actorId,
        action: "ADMIT",
        entity: "Student",
        recordId: student.id,
        newValue: {
          matricNumber: student.matricNumber,
          programmeId: input.programmeId,
          admissionSession: input.admissionSession,
        },
      });

      return { student, enrollment };
    });
  }
}
